---
apiVersion: v1
kind: Namespace
metadata:
  name: books-dev
  labels:
    istio-injection: enabled

#---
#apiVersion: "authentication.istio.io/v1alpha1"
#kind: "Policy"
#metadata:
#  name: "default"
#  namespace: "foo"
#spec:
#  peers:
#    - mtls: {}