---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: legacy
  labels:
    app: httpbin
    namespace: legacy
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 80
  selector:
    app: httpbin

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
  namespace: legacy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
        namespace: legacy
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: legacy
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
  namespace: legacy
spec:
  hosts:
    - "*"
  gateways:
    - httpbin-gateway
  http:
    - match:
      route:
        - destination:
            host: httpbin
            port:
              number: 8000
