---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep
  namespace: version2

---
apiVersion: v1
kind: Service
metadata:
  name: sleep
  namespace: version2
  labels:
    app: sleep
    namespace: version2
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: sleep

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
  namespace: version2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sleep
        namespace: version2
    spec:
      serviceAccountName: sleep
      containers:
        - name: sleep
          image: pstauffer/curl
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent