## global mesh
#---
#apiVersion: "authentication.istio.io/v1alpha1"
#kind: "MeshPolicy"
#metadata:
#  name: "default"
#spec:
#  peers:
#    - mtls: {}
#
# global clients
#---
#apiVersion: "networking.istio.io/v1alpha3"
#kind: "DestinationRule"
#metadata:
#  name: "default"
#  namespace: "default"
#spec:
#  host: "*.local"
#  trafficPolicy:
#    tls:
#      mode: ISTIO_MUTUAL

---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: version1
spec:
  peers:
    - mtls: {}


---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: default
  namespace: version2
spec:
  peers:
    - mtls: {}
#
#---
#apiVersion: authentication.istio.io/v1alpha1
#kind: Policy
#metadata:
#  name: default
#  namespace: version2
#spec:
#  peers:
#    - mtls: {}
#
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: default
#  namespace: version1
#spec:
#  host: "*.version1.svc.cluster.local"
#  trafficPolicy:
#    tls:
#      mode: ISTIO_MUTUAL
