---
apiVersion: v1
kind: Namespace
metadata:
  name: version1
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: version2
  labels:
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: legacy